### ISSUE TITLE
Javascript version

### ISSUE THREAD

**Issue by JurgenJocubeit** [KyleAMathews/typography.js#11]
Is there a way to get a dist (transpiled) version as plain Javascript? I don't use npm, or coffeescript in my project but would love to try this component?

**Comment by KyleAMathews** [comment]
How do you add React components to your apps? Just download and them add them as script tags?

Also another way to try this out is to copy the generated css the playground site outputs

http://kyleamathews.github.io/typography.js/#/configuration

**Comment by KyleAMathews** [comment]
(you can use the default Lato config or some that I've been collecting @ https://github.com/KyleAMathews/typography.js/issues/10)

**Comment by MeetDom** [comment]
Thanks, I appreciate your fast response.

I have a custom media delivery service, but essentially yes I serve the react component via a script tag, they are bundled into a single cached js. I don't use coffeescript at all and would prefer not to have to transpile from cjsx to jsx to js. I can manually convert your cjsx source to js myself but wanted to check if there is a way to get npm/node.js to do it, or even whether you were planning on providing a dist version.

I've just noticed you have a few other really nice components that are all cjsx also.

**Comment by KyleAMathews** [comment]
How do you do the bundling?

**Comment by MeetDom** [comment]
Component source is stored in a database, and a server-side service minifies and concatenates scripts into a single media resource. Everytime a script is updated it is transpiled from JSX to JS automatically  and an etag generated for the cache. Dependencies are handled by the same system. The scripts are all editable from the browser and are transpiled server-side by node.js. React components are rendered server-side to HTML and then reactivated by the browser client-side (isomorphic setup). Node.js does the JSX->JS and component render, but I'm reluctant to add node modules as dependencies (using require) as it makes it very difficult to control the entire pipeline. For other components I'm serving that have dependencies, I add the scripts to the system and a dependency manager handles the load order etc. The system works very well, is extremely fast and only requires a single outbound call to a cached script.  Node.js does not provide any forward facing activity and simply acts as a pipeline to transpile from JSX and render components for the intial view on the server-side. Similar to the react-rails gem, but I don't use sprockets, store physcial files or use coffeescript.

**Comment by MeetDom** [comment]
I just found that Node will create a dist folder with JS and will do the same for each dependency also.

**Comment by KyleAMathews** [comment]
Huh, cool setup :)

Yeah, if you run `make build` it'll compile all the files to ES5 JS. Can your system handle commonjs? If so, you should be set at that point. I distribute the compiled version through NPM but haven't here as I hate checking it compiled code.

**Comment by KyleAMathews** [comment]
Code in ES2015 now and you can find a compiled version at https://npmcdn.com/typography@0.9.1/dist/index.js
