### ISSUE TITLE
"typography.scale" is not a function with Next.js

### ISSUE THREAD

**Issue by valeriashpiner** [KyleAMathews/typography.js#117]
First of all, thank for Typography

I use for my project Next.js and would like to use Typography here.
I receive the error TypeError: (0, _typography.scale) is not a function and, unfortunately, don't understand why, because on my previous project with Gatsby it works great. 

```
import Link from 'next/link'
import typography, { rhythm, scale } from '../utils/typography';
import colors from '../utils/colors';

const HeaderLink = {
  ...scale(-1/4),
  marginRight: rhythm(1),
  color: colors.gunsmoke
}

export default () => (
  <header>
      <a style={HeaderLink} href="/#top">Home</a>
  </header>
)
```
Modules: 
```
"react-typography": "^0.15.10",
"typography": "^0.15.12",
"typography-breakpoint-constants": "^0.15.10"
```

**Comment by KyleAMathews** [comment]
I think the problem is you're using Next not Gatsby ;-)

More seriously, I don't think you can do `import typography, { rhythm, scale }`. It should be either `import typography` or `import {rhythm, scale}`.
