### ISSUE TITLE
Fallback fonts don't seem to work

### ISSUE THREAD

**Issue by daaain** [KyleAMathews/typography.js#122]
It seems there's no way to get the system fallback fonts working :(

For example if I use `headerFontFamily: ['Arial', 'sans-serif']` the browser will ignore `sans-serif` in the CSS due to the quotes, but if I remove the quotes and use `headerFontFamily: ['Arial', sans-serif]` then Javascript breaks.

Am I missing something blindingly obvious?

**Comment by KyleAMathews** [comment]
Oh hmmmm all browsers break on this? I thought quotes around font names were fine.

**Comment by KyleAMathews** [comment]
Oooo… https://stackoverflow.com/a/13752149/182702

Did not know this 😅 would you like to PR a fix? Basically check for the special CSS defined generic names and add them to our generated CSS string without quotes.

**Comment by TrevorBurnham** [comment]
I ran into this today. Here's an attempt at patching this behavior: #125

**Comment by daaain** [comment]
Ah thanks a lot @TrevorBurnham, I just haven't got the time to have a look at this yet!

I just submitted a PR to complete the list of generics, see: #126
