### ISSUE TITLE
a script to generate CSS from typography.js

### ISSUE THREAD

**Issue by heyeshuang** [KyleAMathews/typography.js#140]
Hello,

I found this toolkit very powerful for blogging, however is a bit large to import. So I wrote a simple [script](https://github.com/heyeshuang/typography2css) to export CSS styles from typography themes. Hope it helps a little.

**Comment by KyleAMathews** [comment]
Nice! Thanks for sharing! Would you like to add it to the README for others to find who might be interested?

**Comment by heyeshuang** [comment]
I'll be happy a whole day for that😆
