### ISSUE TITLE
gatsby develop error after installing gatsby-plugin-typography - cannot find module 'amdefine'

### ISSUE THREAD

**Issue by jaegz** [KyleAMathews/typography.js#146]
**System**
`Windows 7 64`
`Node 8.9.1`
`Npm 5.0.3`
`Gatsby 1.1.25`

**Development server fires up just fine when:**
`gatsby new tutorial-part-two https://github.com/gatsbyjs/gatsby-starter-hello-world`
`gatsby develop`

**But after installing the typography plugin, an error occurs:**
`npm install --save gatsby-plugin-typography`
created `gatsby-config.js` in the root folder (_tutorial-part-two_)
`gatsby develop`

```
..\..\AppData\Roaming\npm\node_modules\gatsby-cli\lib\index.js develop

Options:
  -h, --help     Show help                                                                                                  [boolean]

  --verbose      Turn on verbose output                                                                    [boolean] [default: false]

  -H, --host     Set host. Defaults to localhost                                                      [string] [default: "localhost"]

  -p, --port     Set port. Defaults to 8000                                                                [string] [default: "8000"]

  -o, --open     Open the site in your browser for you.                                                                     [boolean]

  -v, --version  Show version number                                                                                        [boolean]


error There was a problem loading the local develop command. Gatsby may not be installed.


  Error: Cannot find module 'amdefine'

  - module.js:11 require
    internal/module.js:11:18

  - source-map-generator.js:8 Object.<anonymous>
    [tutorial-part-two]/[webpack]/[webpack-core]/[source-map]/lib/source-map/source-map-generator.js:8:18

  - module.js:11 require
    internal/module.js:11:18

  - source-map.js:6 Object.<anonymous>
    [tutorial-part-two]/[webpack]/[webpack-core]/[source-map]/lib/source-map.js:6:30
```

**Comment by jason-hunt** [comment]
Same issue.  Just going through the tutorial, but it doesn't work.

**Comment by juanbono** [comment]
Same issue. I have created a new project using the CLI `gatsby new new-site`, then i installed typography by running `npm install --save gatsby-plugin-typography` and adding the plugin to my gastby-config.js file.

**Comment by KyleAMathews** [comment]
Sorry y'all are running into trouble... these sound like problems with installing modules. Try like @juanbono did and reinstalling Gatsby or removing `node_modules` altogether and running `npm install` again.

**Comment by jaegz** [comment]
In my case, removing `node_modules` and running `npm install` produced the same error as in my initial comment. However like @juanbono,  `npm install --save gatsby` did the trick.
