### ISSUE TITLE
Line height gets set in em instead of unitless

### ISSUE THREAD

**Issue by sloria** [KyleAMathews/typography.js#148]
According to the docs,

> baseLineHeight: The base line height using the css unitless number, defaults to 1.5.

However, `line-height` gets set in `em` units.

<img width="600" alt="typography js 2018-01-19 20-17-20" src="https://user-images.githubusercontent.com/2379650/35150628-0ed454fe-fd56-11e7-90c4-5a51dea71b85.png">

**Comment by sloria** [comment]
It's possible I"m just misunderstanding the docs and that using `em` is expected. 

I still think setting unit-less `line-height` is the desired behavior. 

From https://css-tricks.com/almanac/properties/l/line-height/ :

> Unitless line heights are recommended due to the fact that child elements will inherit the raw number value, rather than the computed value. With this, child elements can compute their line heights based on their computed font size, rather than inheriting an arbitrary value from a parent that is more likely to need overriding.

**Comment by sloria** [comment]
The source of the issue is here:

https://github.com/KyleAMathews/compass-vertical-rhythm/blob/master/src/index.coffee#L65

I'm unsure if this is intentional or an oversight.

**Comment by KyleAMathews** [comment]
My memory is that there's some reason to use em when setting the base line-height on `html` — perhaps for legacy browser support. I don't remember why though now and some quick googling didn't help :-)

But as it is, the rest of the line-heights are unitless as you're correct, that is the recommended pattern.

**Comment by sloria** [comment]
OK, thanks for digging into that. 

I did get bit by this; the default line height (1.5em) is inappropriate when the `font-size` for non-headers is larger.

<img width="700" alt="2018-01-20 06-49-36" src="https://user-images.githubusercontent.com/2379650/35175353-3fae4d66-fdae-11e7-84ee-c7811517bf57.png">

I worked around the issue with this:

```javascript
  overrideStyles: () => ({
    html: {
      lineHeight: 1.5,
    },
  }),
```

@KyleAMathews Would you accept a fix in compass-vertical-rhythm for this?

**Comment by KyleAMathews** [comment]
Yeah for sure — that I couldn't find anything suggesting you do things this way suggest perhaps I just made a mistake back in the day :-)

**Comment by sloria** [comment]
Cool, thanks. I'm not sure if/when I'll be able to get to work on this but just wanted to make sure it was the right course first.

**Comment by sloria** [comment]
PR sent here: https://github.com/KyleAMathews/compass-vertical-rhythm/pull/2

**Comment by KyleAMathews** [comment]
Awesome! Thanks for working on this. Published 1.4.0 of compass-vertical-rhythm.

**Comment by sloria** [comment]
Thank you. Will you cut a new release of typography that pins to the new version?

**Comment by KyleAMathews** [comment]
That isn't necessary. Just run upgrade to get the latest

**Comment by sloria** [comment]
Ah, right. Forgot that `^1.3.0` would include `1.4.0`. Thanks.

**Comment by dardub** [comment]
This broke my site by the way. All of my line heights were double what they should have been. It's Friday and I had a delivery so I don't really feel like investigating further right now. But thought I should bring this up because this brings breaking changes and I did not bump any of my dependencies.

**Comment by KyleAMathews** [comment]
@dardub hmmm odd — other sites using typography.js didn't have trouble e.g. gatsbyjs.org — would love to hear more about why the change caused you trouble! Perhaps we're misunderstanding the issue and the `em` did matter.

**Comment by dardub** [comment]
@KyleAMathews Hopefully I'm understanding the problem correctly. From the css-tricks article linked.

> Unitless line heights are recommended due to the fact that child elements will inherit the raw number value, rather than the computed value.

The html elements I saw that were affected did not have any line-height properties specifically defined. So previously the line-heights were inherited from the html computed pixel value. With this change any line-heights not specified will now be based on the font-size of the element.

I think this change is probably correct, but at the same time will cause unexpected consequences for existing sites.

**Comment by KyleAMathews** [comment]
What is your `baseLineHeight`?

**Comment by dardub** [comment]
It was 1.666. I changed it to 1.666em but it seems to output 1.666 no matter what I put there.

**Comment by sloria** [comment]
Yeah, it looks like `compass-vertical-rhythm` has code to remove units from baseLineHeight (which gets passed along to establishBaseline in the latest release):

https://github.com/KyleAMathews/compass-vertical-rhythm/blob/master/src/index.coffee#L96

I can make a PR when I get off of work today.

**Comment by dardub** [comment]
I think we also need to keep in mind in the future that when changing a feature that involves css, it can have ***cascading*** effects that can be difficult to surface.

**Comment by KyleAMathews** [comment]
@dardub yeah :-(

@sloria's PR is published so you can include a unit now on `baseLineHeight`

**Comment by dardub** [comment]
Thanks @KyleAMathews and @sloria for looking at this. Apologies if I was being a bit of a brat.

**Comment by KyleAMathews** [comment]
@dardub nah, not breaking people's code is really important! Appreciate you helping us understand what was happening!
