### ISSUE TITLE
Unlink markup from heading size

### ISSUE THREAD

**Issue by tyler-barnes** [KyleAMathews/typography.js#152]
Usually when I'm working I'll set my heading selectors like `h1, .h1 { ... } h2, .h2 { ... }` and so on. This way my styles aren't linked directly to my markup and I can have an h2 that's the size of an h1 without adding multiple h1's to my page (for seo and semantic purposes). Is there a way to add classes to heading elements in typography.js?

**Comment by tyler-barnes** [comment]
Ok so I'm impatient and want this now so I did a little workaround. This should work for anyone else that does this and is using typography.toString(). I'm using gulp just to run typography and write the output to a scss file that I then include into my normal scss.

```
export function replaceAll(str, mapObj) {
  var re = new RegExp(Object.keys(mapObj).join("|"), "gi");

  return str.replace(re, function(matched) {
    return mapObj[matched.toLowerCase()];
  });
}

const typography = new Typography(typographyjsOptions);
const replaceMap = {
  h1: "h1,.h1",
  h2: "h2,.h2",
  h3: "h3,.h3",
  h4: "h4,.h4",
  h5: "h5,.h5",
  h6: "h6,.h6",
  p: "p,.p"
};
const typographyWithClasses = replaceAll(typography.toString(), replaceMap);

gulp.task("typographyjs", function(cb) {
  fs.writeFile(`./scss/universe/_typographyjs.scss`, typographyWithClasses, cb);
});
```

I found a function which runs multiple string replaces over a single string using an object as a map and just string replaced h1 with h1,.h1 and etc.

**Comment by KyleAMathews** [comment]
Typography.js is meant to be something like normalize.css but customizable. So setting styles directly on elements is part of that. Looks like your work around works well though for your use case!
