### ISSUE TITLE
overflowY: scroll set on <html>

### ISSUE THREAD

**Issue by quentin-sommer** [KyleAMathews/typography.js#154]
Hi Kyle,

I was wondering what's the reasoning behind setting `overflow-y: scroll` on the `<html>` tag. Is it only to prevent the window to resize a bit when dynamic content would make the scrollbar appear?

https://github.com/KyleAMathews/typography.js/blob/2db0735d4b95f002eb6859dead66146729840864/packages/typography/src/utils/createStyles.js#L49

**Comment by KyleAMathews** [comment]
Yeah that. I find it a really common source of glitch on SPA apps especially.

**Comment by quentin-sommer** [comment]
Thanks for the quick answer! How would you feel adding an opt out option to the constructor? I'd like to be able to turn it off. Can setup a pr if you're okay

**Comment by lgraziani2712** [comment]
@quentin-sommer you can customize it right now:

```js
import Typography from 'typography';

const typography = new Typography({
  // ...
  overrideStyles: () => ({
    html: {
      overflowY: 'initial',
    },
  }),
});

export default typography;
```

**Comment by quentin-sommer** [comment]
Awesome thanks!
