### ISSUE TITLE
TypeScript Type Definitions

### ISSUE THREAD

**Issue by codytwinton** [KyleAMathews/typography.js#159]
I noticed that there are type definitions for Flow, but not TypeScript. Is there a plan to add TypeScript type support?

**Comment by KyleAMathews** [comment]
Would love a PR for it!

**Comment by codytwinton** [comment]
@KyleAMathews Gotcha. I'll try to get to that.

**Comment by boyeborg** [comment]
I hva a PR in DefinitelyTyped/DefinitelyTyped#28625 for type definitions.

**Comment by hassankhan** [comment]
Just in case anyone needs to type a theme, I did the following for `typography-theme-alton` and it works like a charm:

```typescript
declare module 'typography-theme-alton' {

  import { TypographyOptions } from 'typography';
  const Theme: TypographyOptions;

  export = Theme;
}

```

**Comment by robphoenix** [comment]
These are now available here - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/typography/index.d.ts

install via npm: `npm i @types/typography`

**Comment by codytwinton** [comment]
@robphoenix - Thanks for the heads up!
