### ISSUE TITLE
Easy responsive typography

### ISSUE THREAD

**Issue by KyleAMathews** [KyleAMathews/typography.js#19]
Like what we do for headers but for everything else. Anytime you call `fontSizeToMS` (or perhaps a different function) it should generate media queries rules for each modular-scale defined in the config.

**Comment by KyleAMathews** [comment]
Or perhaps this is best handled by an external module.

**Comment by KyleAMathews** [comment]
Definitely external module. Plenty of JS->CSS tools out there with media query support if someone wants to do this.

**Comment by daaain** [comment]
Just since I got here from searching for a solution and took me while to figure it out, you can now do this:

```
  overrideStyles: ({ adjustFontSizeTo, scale, rhythm }, options) => {
    const styles = {
      [TABLET_MEDIA_QUERY]: {
        html: {
          fontSize: '16px',
        },
      },
    }
```

Please do tell me if this is butchering it though 😸

**Comment by KyleAMathews** [comment]
@daaain that works!
