### ISSUE TITLE
How can I change the max-width?

### ISSUE THREAD

**Issue by izmth** [KyleAMathews/typography.js#203]
I'm using the gatsby-starter-blog.
I want to change the max-width to 800px but I can't found the way do that.

 I tried this but nothing changed.
```
bootstrapThme.overrideThemeStyles = () => ({ 
    'element.style': { maxWidth: '800px' } 
})
```

**Comment by iammatthias** [comment]
@izmth you'll probably get a better answer on the repo for the Gatsby starter: https://github.com/gatsbyjs/gatsby-starter-blog

That said, check out the `maxWidth` value on line 59 in the layout component: https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/src/components/layout.js

**Comment by izmth** [comment]
@iammatthias 
Thank you so much! 
I succeeded in changing max-width.
