### ISSUE TITLE
typography.toString() outputs default theme not the applied theme

### ISSUE THREAD

**Issue by pianomanfrazier** [KyleAMathews/typography.js#205]
I am trying to generate a the themes to put on a static page and it appears that typography.toString() is outputting only the defaults and not the applied theme. Here is what I've done:

```js
const Typography = require('typography');
const theme = require('typography-theme-lincoln');
const typography = new Typography(theme);
...
console.log(typography.toString()); // I use the output to inject into my html header at build time
```
When I look at the header styles they are not 'Varela Round' but the default -apple-system, ..., sans-serif fonts.

I am also able to grab all the google fonts from the theme and I verified that they are being loaded onto the page.

```js
    googleFonts = theme.default.googleFonts;
    let fonts = []
    for (let i in googleFonts) {
      let name = googleFonts[i].name.replace(/\s/g, "+");
      let tempString = `${name}:${googleFonts[i].styles.join(',')}`;
      fonts.push(tempString);
    }
    return `<link href="https://fonts.googleapis.com/css?family=${fonts.join('|')}" rel="stylesheet">`;
```

**Comment by KyleAMathews** [comment]
Not really sure without being able to see your code. Does `toString` not output `Varela Round` at all?

**Comment by pianomanfrazier** [comment]
So here is some more context. I am using the 11ty static generator. At build time I setup the theme and inject the style in the header with a nunjucks template shortcode. See https://github.com/pianomanfrazier/lilypond-in-markdown/blob/53caad5ec054e093452459343f380cebe76bb8b4/.eleventy.js#L59

When I console log the string output there is not Varela Round in the output at all.

Here is the output https://gist.github.com/pianomanfrazier/6855ecc3ad5588b1cdd91a78ffa8ad8b
See line 237

**Comment by KyleAMathews** [comment]
See if you can reproduce this in a plain JS file? No idea how 11ty works.

**Comment by pianomanfrazier** [comment]
I have updated the gist https://gist.github.com/pianomanfrazier/6855ecc3ad5588b1cdd91a78ffa8ad8b
I did just a plain JS file and the output was the same.

```js
const Typography = require('typography');
const theme = require('typography-theme-lincoln');
const typography = new Typography(theme);

console.log(typography.toString());
```

**Comment by KyleAMathews** [comment]
Ah got it. Tried it locally — `typography-theme-lincoln` is an es6 module so you need to require it like this `const theme = require('typography-theme-lincoln').default`. Yeah for having two incompatible module systems!

**Comment by KyleAMathews** [comment]
It'd be great to switch to https://github.com/developit/microbundle as that generates multiple types of bundles so we wouldn't have this problem.

**Comment by jpwilliams** [comment]
Not intending to necro this, but I stumbled across this again. The `.default` fix of course works a charm, but thought I'd chime in to say this tripped me (and so potentially others) up a bit!
