### ISSUE TITLE
How do I display the configuration UI in my web page?

### ISSUE THREAD

**Issue by ashleydavis** [KyleAMathews/typography.js#213]
I have the Typography plugin installed and working in my Gatsby site.

I'm just wondering how I enable the configuration UI? (highlighted in the screenshot below).

![image](https://user-images.githubusercontent.com/625126/58768297-77c1ce00-85dc-11e9-8ed1-1f71e03130cf.png)

**Comment by KyleAMathews** [comment]
The code is in https://github.com/KyleAMathews/typography.js/tree/master/packages/typography-design-tools but it's pretty rough and not sure you'll be able to get it working.

A newer tool is adding support for these sorts of design tooling and is already really awesome — you should check it out and get involved https://github.com/system-ui/theme-ui

**Comment by ashleydavis** [comment]
Thanks, I think the best thing about this is having the UI to experiment with the design of my site.  Wish I could just drop it. I'll take a look at the new tool!
