### ISSUE TITLE
Update to support React 18

### ISSUE THREAD

**Issue by magnusriga** [KyleAMathews/typography.js#303]
The package current only support react up to v17.

Please update to support react 18.

**Comment by KyleAMathews** [comment]
could you PR an update to the peerDependencies?

**Comment by KyleAMathews** [comment]
Actually there is one haha https://github.com/KyleAMathews/typography.js/pull/300

**Comment by KyleAMathews** [comment]
Published

**Comment by idmadj** [comment]
@magnusriga @KyleAMathews Any reason why this is not published? Right now gatsby-plugin-typography and react-typography cannot be used with Gatsby v5 without `--legacy-peer-deps` (😬) because #300 hasn't been published to NPM. Thanks!
