### ISSUE TITLE
Support CSS variables

### ISSUE THREAD

**Issue by nandorojo** [KyleAMathews/typography.js#306]
Currently, `typography` wraps all font names in quotes. This doesn't let you use a font like `'var(--my-font)'`, since it will turn it into a string. The logic is in `wrapFontFamily`.

**Comment by KyleAMathews** [comment]
Happy to take a pr with a fix

**Comment by nandorojo** [comment]
thanks for the fast response, PR opened here: https://github.com/KyleAMathews/typography.js/pull/307
