### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by rozzzly** [KyleAMathews/typography.js#56]
## ... `topography`.**_`js`_ not `.coffee`**

Got some serious _`badfeelsman.jpg`_ upon realizing this was **`.coffee`**

Apparently im not the only one longing for pure js (es6 hopefully) https://github.com/KyleAMathews/typography.js/issues/11

**Comment by KyleAMathews** [comment]
Sorry for the bad feels man :-)

Feel free to add a PR converting the code to ES2015. I've heard nice things about https://github.com/decaffeinate/decaffeinate.

I might do it myself in the next few weeks if you don't beat me to it.

**Comment by rozzzly** [comment]
**Anyway, awesome repo!! I love it!**

I will definitely use this in the future. This makes playing around a breeze. **Modular scale presets are aweeeeeesome.** :heart_eyes: 

I would have PR'd `letter-spacing`--and there's quite a few things to follow... Yet `.coffee` is a turn off. I'm too lazy to tediously write my code in `.coffee` (never used it before) and although I am that guy who would say, "fck-it im porting to es6+"

But alas, I'm pretty busy on a project of my own atm. But I will make this contribution: https://github.com/KyleAMathews/typography.js/issues/57 some toughts that came to me whilst playing with the demo. 


But seriously, consider renaming the repo. Even just dropping the `.js`. You wouldn't take any hits in terms of SEO/exposure; repo is still small enough where the downside is negligible.

**Comment by KyleAMathews** [comment]
@rozzzly btw, transpiled everything to ES2015 recently + add Flow. Been planning up a bunch of changes. Want to use a number of your ideas in #57 Let me know if you circle back to using / helping out here!
