### ISSUE TITLE
Copycat theme of gutenberg?

### ISSUE THREAD

**Issue by stereobooster** [KyleAMathews/typography.js#84]
Just leave it here http://matejlatin.github.io/Gutenberg/. Maybe I will get to it myself

**Comment by KyleAMathews** [comment]
That'd be great! It's a good looking + popular theme. And instead of FF Meta Serif — perhaps use PT Serif as an (open source) replacement.

**Comment by Bubblbu** [comment]
Would love to see this happen! Any updates maybe?

**Comment by wgao19** [comment]
I happen to be working on a gatsby site and explored both typography.js and Gutenberg! For my site on hand I eventually decided to write the typography by myself to practice. However, I'd love to have Gutenberg with Gatsby, that'd a great combination.
@KyleAMathews if no one seems to have been working on this, may I pick this up?

**Comment by KyleAMathews** [comment]
@wgao19 feel free to create one! You can publish the theme to NPM yourself for people to use.
