### ISSUE TITLE
Define font CSS property

### ISSUE THREAD

**Issue by BarryThePenguin** [KyleAMathews/typography.js#87]
[font - CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/font)

Mainly because I use it with [postcss-lh](https://github.com/KolceThompsonCo/postcss-lh)

**Comment by KyleAMathews** [comment]
Fixed in #88

**Comment by BarryThePenguin** [comment]
I didn't get around to implementing this. Now tests are in I can have another go?

**Comment by KyleAMathews** [comment]
Oh my bad — I thought this had been finished for some reason and we'd just forgotten to close it.

**Comment by BarryThePenguin** [comment]
Looking at this again it could either be

```js
styles = setStyles(styles, 'body', {
  font: `${options.baseFontSize}/${options.baseLineHeight} ${options.bodyFontFamily.join(',')}`,
})
```

or

```js
const { fontSize, lineHeight } = vr.establishBaseline()

styles = setStyles(styles, 'body', {
  font: `${fontSize}/${lineHeight} ${options.bodyFontFamily.join(',')}`,
})
```

Either way both end up overriding the `font-size` and `line-height` on the `html` element. So it might be worth defining it all on the `html` element? I'm not sure of the consequence of doing it that way

**Comment by KyleAMathews** [comment]
I define font-size on the `html` element so that we can use `REM` everywhere.

What you're trying to solve is that the plugin needs `font` defined so it can override it? If so, yeah, just combine the font-size/line-height declarations on `html` into one on `font` and I think we're fine then.

**Comment by KyleAMathews** [comment]
https://css-tricks.com/html-vs-body-in-css/

**Comment by BarryThePenguin** [comment]
Awesome, that's exactly what I was looking for
