### ISSUE TITLE
Letter spacing configuration key

### ISSUE THREAD

**Issue by hudat** [KyleAMathews/typography.js#91]
Is there a way to adjust letter spacing? Didn't see a key for it in the demo site

**Comment by hudat** [comment]
Thanks.

Agreed on the letter-spacing as a fallback option. I mostly use it out of necessity when finding a similar font that's narrower/wider isn't viable given constraints.

**Comment by dirtyredz** [comment]
@KyleAMathews can i see an example of how you include global styles inside your utils/typography.js
Im looking to add letter spacing to all my headers and am curious how you approached this as im just using a standard css file to for all h1,h2,etc

Also if you have a link to a blog/tutorial on how to use the overrideStyles id much appreciate it TY.
